-- Seed gym check-in names for SWLA: Breaux Bridge to Vinton, north to Alexandria.
-- Names and city labels only. No coordinates.

insert into public.gym_directory (name, name_key, metro)
values
  ('Red''s Health Club Lafayette', 'red''s health club lafayette', 'Lafayette'),
  ('Red Lerille''s Lafayette', 'red lerille''s lafayette', 'Lafayette'),
  ('Planet Fitness Lafayette (Ambassador Caffery)', 'planet fitness lafayette (ambassador caffery)', 'Lafayette'),
  ('Anytime Fitness Lafayette (Kaliste Saloom)', 'anytime fitness lafayette (kaliste saloom)', 'Lafayette'),
  ('Anytime Fitness Lafayette (Johnston)', 'anytime fitness lafayette (johnston)', 'Lafayette'),
  ('CLUB4 Fitness Lafayette (Ambassador Caffery)', 'club4 fitness lafayette (ambassador caffery)', 'Lafayette'),
  ('CLUB4 Fitness Lafayette (Johnston)', 'club4 fitness lafayette (johnston)', 'Lafayette'),
  ('Snap Fitness Lafayette (Congress)', 'snap fitness lafayette (congress)', 'Lafayette'),
  ('Orangetheory Lafayette', 'orangetheory lafayette', 'Lafayette'),
  ('F45 Training Lafayette', 'f45 training lafayette', 'Lafayette'),
  ('Iron House Lafayette', 'iron house lafayette', 'Lafayette'),
  ('CrossFit Amis Lafayette', 'crossfit amis lafayette', 'Lafayette'),
  ('CrossFit Acadiana Lafayette', 'crossfit acadiana lafayette', 'Lafayette'),
  ('HOTWORX Lafayette (River Ranch)', 'hotworx lafayette (river ranch)', 'Lafayette'),
  ('HOTWORX Lafayette (Midtown)', 'hotworx lafayette (midtown)', 'Lafayette'),
  ('UL Lafayette Rec Center', 'ul lafayette rec center', 'Lafayette'),
  ('Anytime Fitness Broussard', 'anytime fitness broussard', 'Broussard'),
  ('Cajun Fitness Broussard', 'cajun fitness broussard', 'Broussard'),
  ('Snap Fitness Broussard', 'snap fitness broussard', 'Broussard'),
  ('Anytime Fitness Youngsville', 'anytime fitness youngsville', 'Youngsville'),
  ('Cajun Fitness Youngsville', 'cajun fitness youngsville', 'Youngsville'),
  ('Ole Glory Health and Fitness Youngsville', 'ole glory health and fitness youngsville', 'Youngsville'),
  ('Anytime Fitness Carencro', 'anytime fitness carencro', 'Carencro'),
  ('Anytime Fitness Scott', 'anytime fitness scott', 'Scott'),
  ('CrossFit Acadiana Breaux Bridge', 'crossfit acadiana breaux bridge', 'Breaux Bridge'),
  ('Planet Fitness New Iberia', 'planet fitness new iberia', 'New Iberia'),
  ('Anytime Fitness New Iberia', 'anytime fitness new iberia', 'New Iberia'),
  ('Ole Glory Health and Fitness New Iberia', 'ole glory health and fitness new iberia', 'New Iberia'),
  ('Snap Fitness Abbeville', 'snap fitness abbeville', 'Abbeville'),
  ('Planet Fitness Opelousas', 'planet fitness opelousas', 'Opelousas'),
  ('Anytime Fitness Opelousas', 'anytime fitness opelousas', 'Opelousas'),
  ('Cajun Fitness Opelousas', 'cajun fitness opelousas', 'Opelousas'),
  ('Cajun Fitness Eunice', 'cajun fitness eunice', 'Eunice'),
  ('Anytime Fitness Ville Platte', 'anytime fitness ville platte', 'Ville Platte'),
  ('Anytime Fitness Bunkie', 'anytime fitness bunkie', 'Bunkie'),
  ('Cajun Fitness Rayne', 'cajun fitness rayne', 'Rayne'),
  ('Planet Fitness Crowley', 'planet fitness crowley', 'Crowley'),
  ('Anytime Fitness Crowley', 'anytime fitness crowley', 'Crowley'),
  ('Anytime Fitness Jennings', 'anytime fitness jennings', 'Jennings'),
  ('Anytime Fitness Iowa', 'anytime fitness iowa', 'Iowa'),
  ('Planet Fitness Lake Charles (Ryan)', 'planet fitness lake charles (ryan)', 'Lake Charles'),
  ('Anytime Fitness Lake Charles (Nelson)', 'anytime fitness lake charles (nelson)', 'Lake Charles'),
  ('CLUB4 Fitness Lake Charles', 'club4 fitness lake charles', 'Lake Charles'),
  ('Hurricane CrossFit Lake Charles', 'hurricane crossfit lake charles', 'Lake Charles'),
  ('Orangetheory Lake Charles', 'orangetheory lake charles', 'Lake Charles'),
  ('Mayweather Boxing + Fitness Lake Charles', 'mayweather boxing + fitness lake charles', 'Lake Charles'),
  ('Project Fit Lake Charles', 'project fit lake charles', 'Lake Charles'),
  ('Fit Body Boot Camp Lake Charles', 'fit body boot camp lake charles', 'Lake Charles'),
  ('YMCA of Southwest Louisiana', 'ymca of southwest louisiana', 'Lake Charles'),
  ('McNeese Campus Recreation', 'mcneese campus recreation', 'Lake Charles'),
  ('Anytime Fitness Moss Bluff', 'anytime fitness moss bluff', 'Moss Bluff'),
  ('Genesis Fitness Center Westlake', 'genesis fitness center westlake', 'Westlake'),
  ('Anytime Fitness Sulphur', 'anytime fitness sulphur', 'Sulphur'),
  ('All Hours Fitness DeRidder', 'all hours fitness deridder', 'DeRidder'),
  ('Planet Fitness Alexandria', 'planet fitness alexandria', 'Alexandria'),
  ('Anytime Fitness Alexandria (Coliseum)', 'anytime fitness alexandria (coliseum)', 'Alexandria'),
  ('Body Roque Fitness Alexandria', 'body roque fitness alexandria', 'Alexandria'),
  ('Rapides Fitness Center Alexandria', 'rapides fitness center alexandria', 'Alexandria'),
  ('Alexandria Family YMCA', 'alexandria family ymca', 'Alexandria'),
  ('LSUA Fitness Center', 'lsua fitness center', 'Alexandria'),
  ('Anytime Fitness Pineville (Hwy 165)', 'anytime fitness pineville (hwy 165)', 'Pineville'),
  ('Body Roque Fitness Pineville', 'body roque fitness pineville', 'Pineville'),
  ('CrossFit 28 Pineville', 'crossfit 28 pineville', 'Pineville')
on conflict (name_key) do nothing;
