-- Expanded shared catalog toward 400+ movements.
insert into public.exercises (name, category, primary_muscle, equipment, tracking_type, aliases, slug)
values
  ('Incline Barbell Bench Press', 'strength', 'chest', 'free_weight', 'weight_reps', array['Incline BB Bench Press'], 'incline-barbell-bench-press'),
  ('Decline Barbell Bench Press', 'strength', 'chest', 'free_weight', 'weight_reps', array['Decline BB Bench Press'], 'decline-barbell-bench-press'),
  ('Close-Grip Bench Press', 'strength', 'chest', 'free_weight', 'weight_reps', array[]::text[], 'close-grip-bench-press'),
  ('Pause Bench Press', 'strength', 'chest', 'free_weight', 'weight_reps', array[]::text[], 'pause-bench-press'),
  ('Spoto Press', 'strength', 'full_body', 'free_weight', 'weight_reps', array[]::text[], 'spoto-press'),
  ('Floor Press', 'strength', 'full_body', 'free_weight', 'weight_reps', array[]::text[], 'floor-press'),
  ('Barbell Push Press', 'strength', 'full_body', 'free_weight', 'weight_reps', array['BB Push Press'], 'barbell-push-press'),
  ('Barbell Push Jerk', 'strength', 'full_body', 'free_weight', 'weight_reps', array['BB Push Jerk'], 'barbell-push-jerk'),
  ('Seated Barbell Overhead Press', 'strength', 'shoulders', 'free_weight', 'weight_reps', array['Seated BB Overhead Press'], 'seated-barbell-overhead-press'),
  ('Barbell Behind-the-Neck Press', 'strength', 'full_body', 'free_weight', 'weight_reps', array['BB Behind-the-Neck Press'], 'barbell-behind-the-neck-press'),
  ('Landmine Press', 'strength', 'full_body', 'free_weight', 'weight_reps', array[]::text[], 'landmine-press'),
  ('Landmine Row', 'strength', 'back', 'free_weight', 'weight_reps', array[]::text[], 'landmine-row'),
  ('Meadows Row', 'strength', 'back', 'free_weight', 'weight_reps', array[]::text[], 'meadows-row'),
  ('Pendlay Row', 'strength', 'back', 'free_weight', 'weight_reps', array[]::text[], 'pendlay-row'),
  ('Yates Row', 'strength', 'back', 'free_weight', 'weight_reps', array[]::text[], 'yates-row'),
  ('Barbell Shrug', 'strength', 'traps', 'free_weight', 'weight_reps', array['BB Shrug'], 'barbell-shrug'),
  ('Barbell Upright Row', 'strength', 'back', 'free_weight', 'weight_reps', array['BB Upright Row'], 'barbell-upright-row'),
  ('Good Morning', 'strength', 'hamstrings', 'free_weight', 'weight_reps', array[]::text[], 'good-morning'),
  ('Safety Bar Squat', 'strength', 'quads', 'free_weight', 'weight_reps', array[]::text[], 'safety-bar-squat'),
  ('Pause Squat', 'strength', 'quads', 'free_weight', 'weight_reps', array[]::text[], 'pause-squat'),
  ('Box Squat', 'strength', 'quads', 'free_weight', 'weight_reps', array[]::text[], 'box-squat'),
  ('Anderson Squat', 'strength', 'quads', 'free_weight', 'weight_reps', array[]::text[], 'anderson-squat'),
  ('Zercher Squat', 'strength', 'quads', 'free_weight', 'weight_reps', array[]::text[], 'zercher-squat'),
  ('Hatfield Squat', 'strength', 'quads', 'free_weight', 'weight_reps', array[]::text[], 'hatfield-squat'),
  ('Barbell Split Squat', 'strength', 'quads', 'free_weight', 'weight_reps', array['BB Split Squat'], 'barbell-split-squat'),
  ('Barbell Walking Lunge', 'strength', 'quads', 'free_weight', 'weight_reps', array['BB Walking Lunge'], 'barbell-walking-lunge'),
  ('Barbell Reverse Lunge', 'strength', 'quads', 'free_weight', 'weight_reps', array['BB Reverse Lunge'], 'barbell-reverse-lunge'),
  ('Barbell Step-Up', 'strength', 'quads', 'free_weight', 'weight_reps', array['BB Step-Up'], 'barbell-step-up'),
  ('Barbell Hip Thrust Pause', 'strength', 'glutes', 'free_weight', 'weight_reps', array['BB Hip Thrust Pause'], 'barbell-hip-thrust-pause'),
  ('Barbell Glute Bridge', 'strength', 'glutes', 'free_weight', 'weight_reps', array['BB Glute Bridge'], 'barbell-glute-bridge'),
  ('Deficit Deadlift', 'strength', 'hamstrings', 'free_weight', 'weight_reps', array[]::text[], 'deficit-deadlift'),
  ('Rack Pull', 'strength', 'full_body', 'free_weight', 'weight_reps', array[]::text[], 'rack-pull'),
  ('Snatch-Grip Deadlift', 'strength', 'hamstrings', 'free_weight', 'weight_reps', array[]::text[], 'snatch-grip-deadlift'),
  ('Stiff-Leg Deadlift', 'strength', 'hamstrings', 'free_weight', 'weight_reps', array[]::text[], 'stiff-leg-deadlift'),
  ('Trap Bar Deadlift', 'strength', 'hamstrings', 'free_weight', 'weight_reps', array[]::text[], 'trap-bar-deadlift'),
  ('Trap Bar Jump', 'strength', 'full_body', 'free_weight', 'weight_reps', array[]::text[], 'trap-bar-jump'),
  ('Barbell Calf Raise', 'strength', 'calves', 'free_weight', 'weight_reps', array['BB Calf Raise'], 'barbell-calf-raise'),
  ('Barbell Wrist Curl', 'strength', 'biceps', 'free_weight', 'weight_reps', array['BB Wrist Curl'], 'barbell-wrist-curl'),
  ('Barbell Reverse Wrist Curl', 'strength', 'biceps', 'free_weight', 'weight_reps', array['BB Reverse Wrist Curl'], 'barbell-reverse-wrist-curl'),
  ('EZ-Bar Curl', 'strength', 'biceps', 'free_weight', 'weight_reps', array[]::text[], 'ez-bar-curl'),
  ('EZ-Bar Preacher Curl', 'strength', 'biceps', 'free_weight', 'weight_reps', array[]::text[], 'ez-bar-preacher-curl'),
  ('EZ-Bar Skull Crusher', 'strength', 'triceps', 'free_weight', 'weight_reps', array[]::text[], 'ez-bar-skull-crusher'),
  ('JM Press', 'strength', 'triceps', 'free_weight', 'weight_reps', array[]::text[], 'jm-press'),
  ('Barbell Rollout', 'strength', 'core', 'free_weight', 'weight_reps', array['BB Rollout'], 'barbell-rollout'),
  ('Incline Dumbbell Bench Press', 'strength', 'chest', 'free_weight', 'weight_reps', array['Incline DB Bench Press'], 'incline-dumbbell-bench-press'),
  ('Decline Dumbbell Bench Press', 'strength', 'chest', 'free_weight', 'weight_reps', array['Decline DB Bench Press'], 'decline-dumbbell-bench-press'),
  ('Dumbbell Floor Press', 'strength', 'full_body', 'free_weight', 'weight_reps', array['DB Floor Press'], 'dumbbell-floor-press'),
  ('Dumbbell Squeeze Press', 'strength', 'chest', 'free_weight', 'weight_reps', array['DB Squeeze Press'], 'dumbbell-squeeze-press'),
  ('Dumbbell Pullover', 'strength', 'full_body', 'free_weight', 'weight_reps', array['DB Pullover'], 'dumbbell-pullover'),
  ('Incline Dumbbell Fly', 'strength', 'chest', 'free_weight', 'weight_reps', array['Incline DB Fly'], 'incline-dumbbell-fly'),
  ('Dumbbell Arnold Press', 'strength', 'shoulders', 'free_weight', 'weight_reps', array['DB Arnold Press'], 'dumbbell-arnold-press'),
  ('Dumbbell Z Press', 'strength', 'full_body', 'free_weight', 'weight_reps', array['DB Z Press'], 'dumbbell-z-press'),
  ('Dumbbell Push Press', 'strength', 'full_body', 'free_weight', 'weight_reps', array['DB Push Press'], 'dumbbell-push-press'),
  ('Dumbbell Lateral Raise', 'strength', 'back', 'free_weight', 'weight_reps', array['DB Lateral Raise'], 'dumbbell-lateral-raise'),
  ('Dumbbell Front Raise', 'strength', 'full_body', 'free_weight', 'weight_reps', array['DB Front Raise'], 'dumbbell-front-raise'),
  ('Dumbbell Rear Delt Fly', 'strength', 'chest', 'free_weight', 'weight_reps', array['DB Rear Delt Fly'], 'dumbbell-rear-delt-fly'),
  ('Chest-Supported Dumbbell Row', 'strength', 'chest', 'free_weight', 'weight_reps', array['Chest-Supported DB Row'], 'chest-supported-dumbbell-row'),
  ('Dumbbell Seal Row', 'strength', 'back', 'free_weight', 'weight_reps', array['DB Seal Row'], 'dumbbell-seal-row'),
  ('Dumbbell Shrug', 'strength', 'traps', 'free_weight', 'weight_reps', array['DB Shrug'], 'dumbbell-shrug'),
  ('Dumbbell Walking Lunge', 'strength', 'quads', 'free_weight', 'weight_reps', array['DB Walking Lunge'], 'dumbbell-walking-lunge'),
  ('Dumbbell Reverse Lunge', 'strength', 'quads', 'free_weight', 'weight_reps', array['DB Reverse Lunge'], 'dumbbell-reverse-lunge'),
  ('Dumbbell Step-Up', 'strength', 'quads', 'free_weight', 'weight_reps', array['DB Step-Up'], 'dumbbell-step-up'),
  ('Dumbbell Bulgarian Split Squat', 'strength', 'quads', 'free_weight', 'weight_reps', array['DB Bulgarian Split Squat'], 'dumbbell-bulgarian-split-squat'),
  ('Dumbbell Hip Thrust', 'strength', 'glutes', 'free_weight', 'weight_reps', array['DB Hip Thrust'], 'dumbbell-hip-thrust'),
  ('Dumbbell Calf Raise', 'strength', 'calves', 'free_weight', 'weight_reps', array['DB Calf Raise'], 'dumbbell-calf-raise'),
  ('Dumbbell Farmer Carry', 'strength', 'full_body', 'free_weight', 'distance', array['DB Farmer Carry'], 'dumbbell-farmer-carry'),
  ('Dumbbell Suitcase Carry', 'strength', 'full_body', 'free_weight', 'distance', array['DB Suitcase Carry'], 'dumbbell-suitcase-carry'),
  ('Dumbbell Overhead Carry', 'strength', 'shoulders', 'free_weight', 'distance', array['DB Overhead Carry'], 'dumbbell-overhead-carry'),
  ('Concentration Curl', 'strength', 'biceps', 'free_weight', 'weight_reps', array[]::text[], 'concentration-curl'),
  ('Incline Dumbbell Curl', 'strength', 'biceps', 'free_weight', 'weight_reps', array['Incline DB Curl'], 'incline-dumbbell-curl'),
  ('Dumbbell Preacher Curl', 'strength', 'biceps', 'free_weight', 'weight_reps', array['DB Preacher Curl'], 'dumbbell-preacher-curl'),
  ('Dumbbell Spider Curl', 'strength', 'biceps', 'free_weight', 'weight_reps', array['DB Spider Curl'], 'dumbbell-spider-curl'),
  ('Overhead Dumbbell Extension', 'strength', 'shoulders', 'free_weight', 'weight_reps', array['Overhead DB Extension'], 'overhead-dumbbell-extension'),
  ('Dumbbell Floor Skull Crusher', 'strength', 'triceps', 'free_weight', 'weight_reps', array['DB Floor Skull Crusher'], 'dumbbell-floor-skull-crusher'),
  ('Dumbbell Kickback', 'strength', 'glutes', 'free_weight', 'weight_reps', array['DB Kickback'], 'dumbbell-kickback'),
  ('Dumbbell Side Bend', 'strength', 'full_body', 'free_weight', 'weight_reps', array['DB Side Bend'], 'dumbbell-side-bend'),
  ('Weighted Crunch', 'strength', 'core', 'free_weight', 'weight_reps', array[]::text[], 'weighted-crunch'),
  ('Incline Chest Press Machine', 'strength', 'chest', 'machine', 'weight_reps', array['Incline Chest Press machine'], 'incline-chest-press-machine'),
  ('Decline Chest Press Machine', 'strength', 'chest', 'machine', 'weight_reps', array['Decline Chest Press machine'], 'decline-chest-press-machine'),
  ('Iso-Lateral Chest Press', 'strength', 'chest', 'machine', 'weight_reps', array[]::text[], 'iso-lateral-chest-press'),
  ('Cable Crossover High', 'strength', 'chest', 'machine', 'weight_reps', array[]::text[], 'cable-crossover-high'),
  ('Cable Crossover Low', 'strength', 'chest', 'machine', 'weight_reps', array[]::text[], 'cable-crossover-low'),
  ('Pec Deck Reverse', 'strength', 'chest', 'machine', 'weight_reps', array[]::text[], 'pec-deck-reverse'),
  ('Lat Pulldown Wide', 'strength', 'back', 'machine', 'weight_reps', array[]::text[], 'lat-pulldown-wide'),
  ('Lat Pulldown Neutral', 'strength', 'back', 'machine', 'weight_reps', array[]::text[], 'lat-pulldown-neutral'),
  ('Lat Pulldown Close', 'strength', 'back', 'machine', 'weight_reps', array[]::text[], 'lat-pulldown-close'),
  ('Straight-Arm Pulldown', 'strength', 'back', 'machine', 'weight_reps', array[]::text[], 'straight-arm-pulldown'),
  ('Cable Row Wide', 'strength', 'back', 'machine', 'weight_reps', array[]::text[], 'cable-row-wide'),
  ('Cable Row Close', 'strength', 'back', 'machine', 'weight_reps', array[]::text[], 'cable-row-close'),
  ('Chest-Supported T-Bar Row', 'strength', 'chest', 'machine', 'weight_reps', array[]::text[], 'chest-supported-t-bar-row'),
  ('Iso-Lateral Row', 'strength', 'back', 'machine', 'weight_reps', array[]::text[], 'iso-lateral-row'),
  ('Assisted Chin-Up', 'strength', 'back', 'machine', 'weight_reps', array[]::text[], 'assisted-chin-up'),
  ('Smith Machine Incline Press', 'strength', 'back', 'machine', 'weight_reps', array['Smith machine Incline Press'], 'smith-machine-incline-press'),
  ('Smith Machine Overhead Press', 'strength', 'back', 'machine', 'weight_reps', array['Smith machine Overhead Press'], 'smith-machine-overhead-press'),
  ('Smith Machine Lunge', 'strength', 'back', 'machine', 'weight_reps', array['Smith machine Lunge'], 'smith-machine-lunge'),
  ('Smith Machine Calf Raise', 'strength', 'back', 'machine', 'weight_reps', array['Smith machine Calf Raise'], 'smith-machine-calf-raise'),
  ('Leg Press High Foot', 'strength', 'quads', 'machine', 'weight_reps', array[]::text[], 'leg-press-high-foot'),
  ('Leg Press Low Foot', 'strength', 'quads', 'machine', 'weight_reps', array[]::text[], 'leg-press-low-foot'),
  ('Single-Leg Leg Press', 'strength', 'quads', 'machine', 'weight_reps', array[]::text[], 'single-leg-leg-press'),
  ('Hack Squat Narrow', 'strength', 'back', 'machine', 'weight_reps', array[]::text[], 'hack-squat-narrow'),
  ('Pendulum Squat', 'strength', 'quads', 'machine', 'weight_reps', array[]::text[], 'pendulum-squat'),
  ('Belt Squat', 'strength', 'quads', 'machine', 'weight_reps', array[]::text[], 'belt-squat'),
  ('Lying Leg Curl', 'strength', 'biceps', 'machine', 'weight_reps', array[]::text[], 'lying-leg-curl'),
  ('Standing Leg Curl', 'strength', 'biceps', 'machine', 'weight_reps', array[]::text[], 'standing-leg-curl'),
  ('Adductor Machine', 'strength', 'back', 'machine', 'weight_reps', array['Adductor machine'], 'adductor-machine'),
  ('Abductor Machine', 'strength', 'back', 'machine', 'weight_reps', array['Abductor machine'], 'abductor-machine'),
  ('Standing Calf Machine', 'strength', 'back', 'machine', 'weight_reps', array['Standing Calf machine'], 'standing-calf-machine'),
  ('Seated Calf Machine', 'strength', 'back', 'machine', 'weight_reps', array['Seated Calf machine'], 'seated-calf-machine'),
  ('Cable Face Pull', 'strength', 'back', 'machine', 'weight_reps', array[]::text[], 'cable-face-pull'),
  ('Cable Rear Delt Fly', 'strength', 'chest', 'machine', 'weight_reps', array[]::text[], 'cable-rear-delt-fly'),
  ('Cable Front Raise', 'strength', 'full_body', 'machine', 'weight_reps', array[]::text[], 'cable-front-raise'),
  ('Cable Y Raise', 'strength', 'shoulders', 'machine', 'weight_reps', array[]::text[], 'cable-y-raise'),
  ('Cable Hammer Curl', 'strength', 'biceps', 'machine', 'weight_reps', array[]::text[], 'cable-hammer-curl'),
  ('Cable Overhead Extension', 'strength', 'shoulders', 'machine', 'weight_reps', array[]::text[], 'cable-overhead-extension'),
  ('Cable Pushdown V-Bar', 'strength', 'triceps', 'machine', 'weight_reps', array[]::text[], 'cable-pushdown-v-bar'),
  ('Cable Pushdown Rope', 'strength', 'triceps', 'machine', 'weight_reps', array[]::text[], 'cable-pushdown-rope'),
  ('Cable Crunch', 'strength', 'core', 'machine', 'weight_reps', array[]::text[], 'cable-crunch'),
  ('Cable Woodchop', 'strength', 'core', 'machine', 'weight_reps', array[]::text[], 'cable-woodchop'),
  ('Cable Pallof Press', 'strength', 'core', 'machine', 'weight_reps', array[]::text[], 'cable-pallof-press'),
  ('Ab Wheel Machine', 'strength', 'back', 'machine', 'weight_reps', array['Ab Wheel machine'], 'ab-wheel-machine'),
  ('Glute Kickback Machine', 'strength', 'back', 'machine', 'weight_reps', array['Glute Kickback machine'], 'glute-kickback-machine'),
  ('Hip Thrust Machine', 'strength', 'back', 'machine', 'weight_reps', array['Hip Thrust machine'], 'hip-thrust-machine'),
  ('Back Extension Machine', 'strength', 'back', 'machine', 'weight_reps', array['Back Extension machine'], 'back-extension-machine'),
  ('Treadmill Run', 'cardio', 'cardio', 'machine', 'distance', array[]::text[], 'treadmill-run'),
  ('Treadmill Walk', 'cardio', 'cardio', 'machine', 'distance', array[]::text[], 'treadmill-walk'),
  ('Assault Bike', 'cardio', 'cardio', 'machine', 'duration', array[]::text[], 'assault-bike'),
  ('Echo Bike', 'cardio', 'cardio', 'machine', 'duration', array[]::text[], 'echo-bike'),
  ('SkiErg', 'cardio', 'cardio', 'machine', 'duration', array[]::text[], 'skierg'),
  ('Recumbent Bike', 'cardio', 'cardio', 'machine', 'duration', array[]::text[], 'recumbent-bike'),
  ('Knee Push-Up', 'strength', 'full_body', 'bodyweight', 'reps_only', array[]::text[], 'knee-push-up'),
  ('Incline Push-Up', 'strength', 'full_body', 'bodyweight', 'reps_only', array[]::text[], 'incline-push-up'),
  ('Decline Push-Up', 'strength', 'full_body', 'bodyweight', 'reps_only', array[]::text[], 'decline-push-up'),
  ('Diamond Push-Up', 'strength', 'full_body', 'bodyweight', 'reps_only', array[]::text[], 'diamond-push-up'),
  ('Archer Push-Up', 'strength', 'full_body', 'bodyweight', 'reps_only', array[]::text[], 'archer-push-up'),
  ('Pseudo Planche Push-Up', 'strength', 'full_body', 'bodyweight', 'reps_only', array[]::text[], 'pseudo-planche-push-up'),
  ('Pike Push-Up', 'strength', 'full_body', 'bodyweight', 'reps_only', array[]::text[], 'pike-push-up'),
  ('Handstand Hold', 'strength', 'shoulders', 'bodyweight', 'duration', array[]::text[], 'handstand-hold'),
  ('Wall Handstand Push-Up', 'strength', 'shoulders', 'bodyweight', 'reps_only', array[]::text[], 'wall-handstand-push-up'),
  ('Ring Push-Up', 'strength', 'full_body', 'bodyweight', 'reps_only', array[]::text[], 'ring-push-up'),
  ('Ring Row', 'strength', 'back', 'bodyweight', 'reps_only', array[]::text[], 'ring-row'),
  ('Ring Dip', 'strength', 'triceps', 'bodyweight', 'reps_only', array[]::text[], 'ring-dip'),
  ('Negative Pull-Up', 'strength', 'back', 'bodyweight', 'reps_only', array[]::text[], 'negative-pull-up'),
  ('Band-Assisted Pull-Up', 'strength', 'back', 'bodyweight', 'reps_only', array[]::text[], 'band-assisted-pull-up'),
  ('Wide-Grip Pull-Up', 'strength', 'back', 'bodyweight', 'reps_only', array[]::text[], 'wide-grip-pull-up'),
  ('Commando Pull-Up', 'strength', 'back', 'bodyweight', 'reps_only', array[]::text[], 'commando-pull-up'),
  ('Muscle-Up', 'strength', 'full_body', 'bodyweight', 'reps_only', array[]::text[], 'muscle-up'),
  ('Bar Dip', 'strength', 'triceps', 'bodyweight', 'reps_only', array[]::text[], 'bar-dip'),
  ('Bench Dip', 'strength', 'chest', 'bodyweight', 'reps_only', array[]::text[], 'bench-dip'),
  ('Pistol Squat', 'strength', 'quads', 'bodyweight', 'reps_only', array[]::text[], 'pistol-squat'),
  ('Shrimp Squat', 'strength', 'quads', 'bodyweight', 'reps_only', array[]::text[], 'shrimp-squat'),
  ('Cossack Squat', 'strength', 'quads', 'bodyweight', 'reps_only', array[]::text[], 'cossack-squat'),
  ('Jump Squat', 'strength', 'quads', 'bodyweight', 'reps_only', array[]::text[], 'jump-squat'),
  ('Broad Jump', 'strength', 'full_body', 'bodyweight', 'reps_only', array[]::text[], 'broad-jump'),
  ('Tuck Jump', 'strength', 'full_body', 'bodyweight', 'reps_only', array[]::text[], 'tuck-jump'),
  ('Split Squat Jump', 'strength', 'quads', 'bodyweight', 'reps_only', array[]::text[], 'split-squat-jump'),
  ('Nordic Curl', 'strength', 'biceps', 'bodyweight', 'reps_only', array[]::text[], 'nordic-curl'),
  ('Reverse Nordic', 'strength', 'hamstrings', 'bodyweight', 'reps_only', array[]::text[], 'reverse-nordic'),
  ('Sliding Leg Curl', 'strength', 'biceps', 'bodyweight', 'reps_only', array[]::text[], 'sliding-leg-curl'),
  ('Single-Leg Glute Bridge', 'strength', 'glutes', 'bodyweight', 'reps_only', array[]::text[], 'single-leg-glute-bridge'),
  ('Frog Pump', 'strength', 'glutes', 'bodyweight', 'reps_only', array[]::text[], 'frog-pump'),
  ('Hip Airplane', 'strength', 'full_body', 'bodyweight', 'reps_only', array[]::text[], 'hip-airplane'),
  ('Dead Bug', 'strength', 'core', 'bodyweight', 'reps_only', array[]::text[], 'dead-bug'),
  ('Bird Dog', 'strength', 'full_body', 'bodyweight', 'reps_only', array[]::text[], 'bird-dog'),
  ('Hollow Rock', 'strength', 'core', 'bodyweight', 'reps_only', array[]::text[], 'hollow-rock'),
  ('V-Up', 'strength', 'core', 'bodyweight', 'reps_only', array[]::text[], 'v-up'),
  ('Hanging Knee Raise', 'strength', 'full_body', 'bodyweight', 'reps_only', array[]::text[], 'hanging-knee-raise'),
  ('Hanging Leg Raise', 'strength', 'full_body', 'bodyweight', 'reps_only', array[]::text[], 'hanging-leg-raise'),
  ('Toes-to-Bar', 'strength', 'full_body', 'bodyweight', 'reps_only', array[]::text[], 'toes-to-bar'),
  ('L-Sit', 'strength', 'core', 'bodyweight', 'duration', array[]::text[], 'l-sit'),
  ('Plank Shoulder Tap', 'strength', 'shoulders', 'bodyweight', 'duration', array[]::text[], 'plank-shoulder-tap'),
  ('RKC Plank', 'strength', 'core', 'bodyweight', 'duration', array[]::text[], 'rkc-plank'),
  ('Copenhagen Plank', 'strength', 'core', 'bodyweight', 'duration', array[]::text[], 'copenhagen-plank'),
  ('Bear Crawl', 'endurance', 'full_body', 'bodyweight', 'distance', array[]::text[], 'bear-crawl'),
  ('Crab Walk', 'endurance', 'cardio', 'bodyweight', 'distance', array[]::text[], 'crab-walk'),
  ('Inchworm', 'strength', 'full_body', 'bodyweight', 'reps_only', array[]::text[], 'inchworm'),
  ('World''s Greatest Stretch', 'strength', 'full_body', 'bodyweight', 'duration', array[]::text[], 'world-s-greatest-stretch'),
  ('90/90 Hip Switch', 'strength', 'full_body', 'bodyweight', 'reps_only', array[]::text[], '90-90-hip-switch'),
  ('Couch Stretch Hold', 'strength', 'full_body', 'bodyweight', 'duration', array[]::text[], 'couch-stretch-hold'),
  ('Wall Sit', 'strength', 'full_body', 'bodyweight', 'duration', array[]::text[], 'wall-sit'),
  ('Calf Raise Bodyweight', 'strength', 'calves', 'bodyweight', 'reps_only', array[]::text[], 'calf-raise-bodyweight'),
  ('Single-Leg Calf Raise', 'strength', 'calves', 'bodyweight', 'reps_only', array[]::text[], 'single-leg-calf-raise'),
  ('Sled Drag', 'endurance', 'full_body', 'bodyweight', 'distance', array[]::text[], 'sled-drag'),
  ('Farmer Carry Bodyweight March', 'endurance', 'full_body', 'bodyweight', 'distance', array[]::text[], 'farmer-carry-bodyweight-march'),
  ('Band Pull-Apart', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Pull-Apart'], 'band-pull-apart'),
  ('Band Face Pull', 'strength', 'back', 'free_weight', 'weight_reps', array['Face Pull'], 'band-face-pull'),
  ('Band Chest Press', 'strength', 'chest', 'free_weight', 'weight_reps', array['Chest Press'], 'band-chest-press'),
  ('Band Row', 'strength', 'back', 'free_weight', 'weight_reps', array['Row'], 'band-row'),
  ('Band Deadlift', 'strength', 'hamstrings', 'free_weight', 'weight_reps', array['Deadlift'], 'band-deadlift'),
  ('Band Good Morning', 'strength', 'hamstrings', 'free_weight', 'weight_reps', array['Good Morning'], 'band-good-morning'),
  ('Band Squat', 'strength', 'quads', 'free_weight', 'weight_reps', array['Squat'], 'band-squat'),
  ('Band Lateral Walk', 'strength', 'back', 'free_weight', 'weight_reps', array['Lateral Walk'], 'band-lateral-walk'),
  ('Band Glute Kickback', 'strength', 'glutes', 'free_weight', 'weight_reps', array['Glute Kickback'], 'band-glute-kickback'),
  ('Band Bicep Curl', 'strength', 'biceps', 'free_weight', 'weight_reps', array['Bicep Curl'], 'band-bicep-curl'),
  ('Band Tricep Pushdown', 'strength', 'triceps', 'free_weight', 'weight_reps', array['Tricep Pushdown'], 'band-tricep-pushdown'),
  ('Band Pallof Press', 'strength', 'core', 'free_weight', 'weight_reps', array['Pallof Press'], 'band-pallof-press'),
  ('Band Dislocate', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Dislocate'], 'band-dislocate'),
  ('Band Overhead Press', 'strength', 'shoulders', 'free_weight', 'weight_reps', array['Overhead Press'], 'band-overhead-press'),
  ('Band Romanian Deadlift', 'strength', 'hamstrings', 'free_weight', 'weight_reps', array['Romanian Deadlift'], 'band-romanian-deadlift'),
  ('Kettlebell Goblet Squat', 'strength', 'quads', 'free_weight', 'weight_reps', array['Kettlebell Goblet Squat'], 'kettlebell-goblet-squat'),
  ('Kettlebell Front Squat', 'strength', 'quads', 'free_weight', 'weight_reps', array['Kettlebell Front Squat'], 'kettlebell-front-squat'),
  ('Kettlebell Deadlift', 'strength', 'hamstrings', 'free_weight', 'weight_reps', array['Kettlebell Deadlift'], 'kettlebell-deadlift'),
  ('Kettlebell RDL', 'strength', 'hamstrings', 'free_weight', 'weight_reps', array['Kettlebell RDL'], 'kettlebell-rdl'),
  ('Kettlebell Clean', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Kettlebell Clean'], 'kettlebell-clean'),
  ('Kettlebell Snatch', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Kettlebell Snatch'], 'kettlebell-snatch'),
  ('Kettlebell Clean and Press', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Kettlebell Clean and Press'], 'kettlebell-clean-and-press'),
  ('Kettlebell Push Press', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Kettlebell Push Press'], 'kettlebell-push-press'),
  ('Kettlebell Windmill', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Kettlebell Windmill'], 'kettlebell-windmill'),
  ('Kettlebell Halo', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Kettlebell Halo'], 'kettlebell-halo'),
  ('Kettlebell High Pull', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Kettlebell High Pull'], 'kettlebell-high-pull'),
  ('Kettlebell Thruster', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Kettlebell Thruster'], 'kettlebell-thruster'),
  ('Kettlebell Turkish Get-Up', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Kettlebell Turkish Get-Up'], 'kettlebell-turkish-get-up'),
  ('Kettlebell Floor Press', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Kettlebell Floor Press'], 'kettlebell-floor-press'),
  ('Kettlebell Row', 'strength', 'back', 'free_weight', 'weight_reps', array['Kettlebell Row'], 'kettlebell-row'),
  ('Kettlebell Bottoms-Up Press', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Kettlebell Bottoms-Up Press'], 'kettlebell-bottoms-up-press'),
  ('Cable Kickback', 'strength', 'glutes', 'free_weight', 'weight_reps', array['Cable Kickback'], 'cable-kickback'),
  ('Cable Pull-Through', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Cable Pull-Through'], 'cable-pull-through'),
  ('Cable Hip Abduction', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Cable Hip Abduction'], 'cable-hip-abduction'),
  ('Single-Arm Cable Chest Press', 'strength', 'chest', 'free_weight', 'weight_reps', array['Single-Arm Cable Chest Press'], 'single-arm-cable-chest-press'),
  ('Single-Arm Cable Row', 'strength', 'back', 'free_weight', 'weight_reps', array['Single-Arm Cable Row'], 'single-arm-cable-row'),
  ('Cable External Rotation', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Cable External Rotation'], 'cable-external-rotation'),
  ('Smith Machine Decline Press', 'strength', 'back', 'free_weight', 'weight_reps', array['Smith Machine Decline Press'], 'smith-machine-decline-press'),
  ('Smith Machine Row', 'strength', 'back', 'free_weight', 'weight_reps', array['Smith Machine Row'], 'smith-machine-row'),
  ('Smith Machine Hip Thrust', 'strength', 'back', 'free_weight', 'weight_reps', array['Smith Machine Hip Thrust'], 'smith-machine-hip-thrust'),
  ('Smith Machine Romanian Deadlift', 'strength', 'back', 'free_weight', 'weight_reps', array['Smith Machine Romanian Deadlift'], 'smith-machine-romanian-deadlift'),
  ('Outdoor Sprint Intervals', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Outdoor Sprint Intervals'], 'outdoor-sprint-intervals'),
  ('Hill Repeat Run', 'strength', 'cardio', 'free_weight', 'weight_reps', array['Hill Repeat Run'], 'hill-repeat-run'),
  ('Tempo Run', 'strength', 'cardio', 'free_weight', 'weight_reps', array['Tempo Run'], 'tempo-run'),
  ('Easy Jog', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Easy Jog'], 'easy-jog'),
  ('Ruck Walk', 'strength', 'cardio', 'free_weight', 'weight_reps', array['Ruck Walk'], 'ruck-walk'),
  ('Jump Rope Intervals', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Jump Rope Intervals'], 'jump-rope-intervals'),
  ('Shadow Boxing', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Shadow Boxing'], 'shadow-boxing'),
  ('Swim Freestyle', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Swim Freestyle'], 'swim-freestyle'),
  ('Power Clean', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Power Clean'], 'power-clean'),
  ('Hang Clean', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Hang Clean'], 'hang-clean'),
  ('Power Snatch', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Power Snatch'], 'power-snatch'),
  ('Hang Snatch', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Hang Snatch'], 'hang-snatch'),
  ('Push Jerk', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Push Jerk'], 'push-jerk'),
  ('Split Jerk', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Split Jerk'], 'split-jerk'),
  ('Overhead Squat', 'strength', 'shoulders', 'free_weight', 'weight_reps', array['Overhead Squat'], 'overhead-squat'),
  ('Suitcase Deadlift', 'strength', 'hamstrings', 'free_weight', 'weight_reps', array['Suitcase Deadlift'], 'suitcase-deadlift'),
  ('Waiter Carry', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Waiter Carry'], 'waiter-carry'),
  ('Front Rack Carry', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Front Rack Carry'], 'front-rack-carry'),
  ('Sandbag Clean', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Sandbag Clean'], 'sandbag-clean'),
  ('Sandbag Bear Hug Squat', 'strength', 'quads', 'free_weight', 'weight_reps', array['Sandbag Bear Hug Squat'], 'sandbag-bear-hug-squat'),
  ('Tire Flip', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Tire Flip'], 'tire-flip'),
  ('Medicine Ball Chest Pass', 'strength', 'chest', 'free_weight', 'weight_reps', array['Medicine Ball Chest Pass'], 'medicine-ball-chest-pass'),
  ('Landmine Rotation', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Landmine Rotation'], 'landmine-rotation'),
  ('Landmine Squat to Press', 'strength', 'quads', 'free_weight', 'weight_reps', array['Landmine Squat to Press'], 'landmine-squat-to-press'),
  ('Pause Deadlift', 'strength', 'hamstrings', 'free_weight', 'weight_reps', array['Pause Deadlift'], 'pause-deadlift'),
  ('Tempo Squat', 'strength', 'quads', 'free_weight', 'weight_reps', array['Tempo Squat'], 'tempo-squat'),
  ('Pin Bench Press', 'strength', 'chest', 'free_weight', 'weight_reps', array['Pin Bench Press'], 'pin-bench-press'),
  ('Swiss Bar Bench', 'strength', 'chest', 'free_weight', 'weight_reps', array['Swiss Bar Bench'], 'swiss-bar-bench'),
  ('Neutral-Grip Pull-Up', 'strength', 'back', 'free_weight', 'weight_reps', array['Neutral-Grip Pull-Up'], 'neutral-grip-pull-up'),
  ('Clap Push-Up', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Clap Push-Up'], 'clap-push-up'),
  ('Hindu Push-Up', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Hindu Push-Up'], 'hindu-push-up'),
  ('Dead Hang', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Dead Hang'], 'dead-hang'),
  ('YTW Raise', 'strength', 'full_body', 'free_weight', 'weight_reps', array['YTW Raise'], 'ytw-raise'),
  ('Wall Slide', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Wall Slide'], 'wall-slide'),
  ('McGill Curl-Up', 'strength', 'biceps', 'free_weight', 'weight_reps', array['McGill Curl-Up'], 'mcgill-curl-up'),
  ('Stir the Pot', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Stir the Pot'], 'stir-the-pot'),
  ('Scapular Pull-Up', 'strength', 'back', 'free_weight', 'weight_reps', array['Scapular Pull-Up'], 'scapular-pull-up'),
  ('Prone Cobra', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Prone Cobra'], 'prone-cobra'),
  ('Cat Cow', 'strength', 'full_body', 'free_weight', 'weight_reps', array['Cat Cow'], 'cat-cow'),
  ('Pause RDL', 'strength', 'hamstrings', 'free_weight', 'weight_reps', array[]::text[], 'pause-rdl'),
  ('Sumo Pause Deadlift', 'strength', 'hamstrings', 'free_weight', 'weight_reps', array[]::text[], 'sumo-pause-deadlift'),
  ('Jefferson Deadlift', 'strength', 'hamstrings', 'free_weight', 'weight_reps', array[]::text[], 'jefferson-deadlift'),
  ('Board Press', 'strength', 'full_body', 'free_weight', 'weight_reps', array[]::text[], 'board-press'),
  ('Pin Squat', 'strength', 'quads', 'bodyweight', 'reps_only', array[]::text[], 'pin-squat'),
  ('Swiss Bar Overhead Press', 'strength', 'shoulders', 'free_weight', 'weight_reps', array[]::text[], 'swiss-bar-overhead-press'),
  ('Cambered Bar Bench', 'strength', 'chest', 'free_weight', 'weight_reps', array[]::text[], 'cambered-bar-bench'),
  ('Barbell Curl 21s', 'strength', 'biceps', 'free_weight', 'weight_reps', array['BB Curl 21s'], 'barbell-curl-21s'),
  ('Close-Grip Incline Bench', 'strength', 'chest', 'free_weight', 'weight_reps', array[]::text[], 'close-grip-incline-bench'),
  ('Dumbbell Cuban Press', 'strength', 'full_body', 'free_weight', 'weight_reps', array['DB Cuban Press'], 'dumbbell-cuban-press'),
  ('Renegade Row', 'strength', 'back', 'free_weight', 'weight_reps', array[]::text[], 'renegade-row'),
  ('Dumbbell Thruster', 'strength', 'full_body', 'free_weight', 'weight_reps', array['DB Thruster'], 'dumbbell-thruster'),
  ('Dumbbell Snatch', 'strength', 'full_body', 'free_weight', 'weight_reps', array['DB Snatch'], 'dumbbell-snatch'),
  ('Dumbbell Clean', 'strength', 'full_body', 'free_weight', 'weight_reps', array['DB Clean'], 'dumbbell-clean'),
  ('Single-Arm Dumbbell Bench', 'strength', 'chest', 'free_weight', 'weight_reps', array['Single-Arm DB Bench'], 'single-arm-dumbbell-bench'),
  ('Dumbbell Deficit RDL', 'strength', 'hamstrings', 'free_weight', 'weight_reps', array['DB Deficit RDL'], 'dumbbell-deficit-rdl'),
  ('Tate Press', 'strength', 'full_body', 'free_weight', 'weight_reps', array[]::text[], 'tate-press'),
  ('Cross-Body Hammer Curl', 'strength', 'biceps', 'free_weight', 'weight_reps', array[]::text[], 'cross-body-hammer-curl'),
  ('Hammer Strength Iso Row', 'strength', 'back', 'free_weight', 'weight_reps', array[]::text[], 'hammer-strength-iso-row'),
  ('Reverse Hyper', 'strength', 'full_body', 'machine', 'weight_reps', array[]::text[], 'reverse-hyper'),
  ('GHD Hip Extension', 'strength', 'triceps', 'machine', 'weight_reps', array[]::text[], 'ghd-hip-extension'),
  ('GHD Sit-Up', 'strength', 'full_body', 'machine', 'duration', array[]::text[], 'ghd-sit-up'),
  ('Vertical Leg Press', 'strength', 'quads', 'free_weight', 'weight_reps', array[]::text[], 'vertical-leg-press'),
  ('Preacher Curl Machine', 'strength', 'back', 'machine', 'weight_reps', array['Preacher Curl machine'], 'preacher-curl-machine'),
  ('Tricep Dip Machine', 'strength', 'back', 'machine', 'weight_reps', array['Tricep Dip machine'], 'tricep-dip-machine'),
  ('Ab Crunch Machine', 'strength', 'back', 'machine', 'weight_reps', array['Ab Crunch machine'], 'ab-crunch-machine'),
  ('Stair Climber', 'cardio', 'cardio', 'machine', 'duration', array[]::text[], 'stair-climber'),
  ('Jacob''s Ladder', 'cardio', 'cardio', 'free_weight', 'duration', array[]::text[], 'jacob-s-ladder'),
  ('Row Erg Steady State', 'cardio', 'cardio', 'machine', 'duration', array[]::text[], 'row-erg-steady-state'),
  ('Air Bike Intervals', 'cardio', 'cardio', 'free_weight', 'duration', array[]::text[], 'air-bike-intervals'),
  ('Elliptical', 'cardio', 'cardio', 'machine', 'duration', array[]::text[], 'elliptical'),
  ('Archer Pull-Up', 'strength', 'back', 'bodyweight', 'distance', array[]::text[], 'archer-pull-up'),
  ('Chest-to-Bar Pull-Up', 'strength', 'chest', 'bodyweight', 'distance', array[]::text[], 'chest-to-bar-pull-up'),
  ('Jumping Pull-Up', 'strength', 'back', 'bodyweight', 'distance', array[]::text[], 'jumping-pull-up'),
  ('Skin the Cat', 'strength', 'cardio', 'free_weight', 'weight_reps', array[]::text[], 'skin-the-cat'),
  ('Front Lever Tuck', 'strength', 'full_body', 'bodyweight', 'weight_reps', array[]::text[], 'front-lever-tuck'),
  ('Planche Lean', 'strength', 'full_body', 'bodyweight', 'weight_reps', array[]::text[], 'planche-lean'),
  ('Handstand Walk', 'strength', 'shoulders', 'bodyweight', 'duration', array[]::text[], 'handstand-walk'),
  ('Plyo Push-Up', 'strength', 'full_body', 'bodyweight', 'distance', array[]::text[], 'plyo-push-up'),
  ('Sissy Squat', 'strength', 'quads', 'bodyweight', 'reps_only', array[]::text[], 'sissy-squat'),
  ('ATG Split Squat', 'strength', 'quads', 'bodyweight', 'reps_only', array[]::text[], 'atg-split-squat'),
  ('Lateral Lunge', 'strength', 'back', 'bodyweight', 'reps_only', array[]::text[], 'lateral-lunge'),
  ('Curtsy Lunge', 'strength', 'quads', 'bodyweight', 'reps_only', array[]::text[], 'curtsy-lunge'),
  ('Jumping Lunge', 'strength', 'quads', 'bodyweight', 'reps_only', array[]::text[], 'jumping-lunge'),
  ('Box Jump', 'strength', 'full_body', 'bodyweight', 'reps_only', array[]::text[], 'box-jump'),
  ('Depth Jump', 'strength', 'full_body', 'bodyweight', 'reps_only', array[]::text[], 'depth-jump'),
  ('Burpee', 'strength', 'full_body', 'bodyweight', 'reps_only', array[]::text[], 'burpee'),
  ('Mountain Climber', 'cardio', 'cardio', 'machine', 'duration', array[]::text[], 'mountain-climber'),
  ('High Knees', 'cardio', 'cardio', 'free_weight', 'duration', array[]::text[], 'high-knees'),
  ('Jumping Jack', 'cardio', 'cardio', 'bodyweight', 'duration', array[]::text[], 'jumping-jack'),
  ('Superman Hold', 'strength', 'full_body', 'bodyweight', 'duration', array[]::text[], 'superman-hold'),
  ('Side Plank Hip Dip', 'strength', 'triceps', 'bodyweight', 'reps_only', array[]::text[], 'side-plank-hip-dip'),
  ('Hollow Hold', 'strength', 'core', 'bodyweight', 'duration', array[]::text[], 'hollow-hold'),
  ('Dragon Flag Negative', 'strength', 'full_body', 'free_weight', 'weight_reps', array[]::text[], 'dragon-flag-negative'),
  ('Clean Pull', 'strength', 'full_body', 'free_weight', 'distance', array[]::text[], 'clean-pull'),
  ('Snatch Pull', 'strength', 'full_body', 'free_weight', 'distance', array[]::text[], 'snatch-pull'),
  ('Hang Power Clean', 'strength', 'full_body', 'free_weight', 'weight_reps', array[]::text[], 'hang-power-clean'),
  ('Hang Power Snatch', 'strength', 'full_body', 'free_weight', 'weight_reps', array[]::text[], 'hang-power-snatch'),
  ('Muscle Snatch', 'strength', 'full_body', 'free_weight', 'weight_reps', array[]::text[], 'muscle-snatch'),
  ('Log Press', 'strength', 'full_body', 'free_weight', 'weight_reps', array[]::text[], 'log-press'),
  ('Yoke Carry', 'strength', 'full_body', 'free_weight', 'distance', array[]::text[], 'yoke-carry'),
  ('Farmers Walk Heavy', 'strength', 'cardio', 'free_weight', 'duration', array[]::text[], 'farmers-walk-heavy'),
  ('Sled Push', 'strength', 'full_body', 'free_weight', 'distance', array[]::text[], 'sled-push'),
  ('Sled Pull', 'strength', 'full_body', 'free_weight', 'distance', array[]::text[], 'sled-pull'),
  ('Battle Rope Waves', 'strength', 'full_body', 'free_weight', 'weight_reps', array[]::text[], 'battle-rope-waves'),
  ('Medicine Ball Slam', 'strength', 'full_body', 'free_weight', 'weight_reps', array[]::text[], 'medicine-ball-slam'),
  ('Wall Ball', 'strength', 'full_body', 'free_weight', 'weight_reps', array[]::text[], 'wall-ball'),
  ('Rotational Med Ball Throw', 'strength', 'back', 'free_weight', 'weight_reps', array[]::text[], 'rotational-med-ball-throw'),
  ('Banded Hip Turn', 'strength', 'full_body', 'free_weight', 'weight_reps', array[]::text[], 'banded-hip-turn'),
  ('Lateral Bound', 'strength', 'back', 'free_weight', 'weight_reps', array[]::text[], 'lateral-bound'),
  ('A-Skip', 'cardio', 'cardio', 'bodyweight', 'duration', array[]::text[], 'a-skip'),
  ('Carioca', 'cardio', 'cardio', 'bodyweight', 'duration', array[]::text[], 'carioca'),
  ('Half Kneeling Chop', 'strength', 'full_body', 'free_weight', 'weight_reps', array[]::text[], 'half-kneeling-chop'),
  ('Cable Lateral Raise', 'strength', 'back', 'free_weight', 'weight_reps', array[]::text[], 'cable-lateral-raise'),
  ('Cable Upright Row', 'strength', 'back', 'free_weight', 'weight_reps', array[]::text[], 'cable-upright-row'),
  ('Low Cable Row', 'strength', 'back', 'free_weight', 'weight_reps', array[]::text[], 'low-cable-row'),
  ('High Cable Row', 'strength', 'back', 'free_weight', 'weight_reps', array[]::text[], 'high-cable-row'),
  ('Pec Deck Fly', 'strength', 'chest', 'machine', 'weight_reps', array[]::text[], 'pec-deck-fly'),
  ('Shoulder Press Machine', 'strength', 'back', 'machine', 'weight_reps', array['Shoulder Press machine'], 'shoulder-press-machine'),
  ('Hack Squat Wide', 'strength', 'quads', 'bodyweight', 'reps_only', array[]::text[], 'hack-squat-wide'),
  ('Belt Squat March', 'strength', 'quads', 'bodyweight', 'duration', array[]::text[], 'belt-squat-march'),
  ('Neck Harness', 'strength', 'full_body', 'free_weight', 'weight_reps', array[]::text[], 'neck-harness'),
  ('Wrist Roller', 'strength', 'forearms', 'free_weight', 'weight_reps', array[]::text[], 'wrist-roller'),
  ('Seated Dip Machine', 'strength', 'back', 'machine', 'weight_reps', array['Seated Dip machine'], 'seated-dip-machine'),
  ('Torso Rotation Machine', 'strength', 'back', 'machine', 'weight_reps', array['Torso Rotation machine'], 'torso-rotation-machine'),
  ('VersaClimber', 'cardio', 'cardio', 'machine', 'duration', array[]::text[], 'versaclimber'),
  ('Typewriter Pull-Up', 'strength', 'back', 'bodyweight', 'distance', array[]::text[], 'typewriter-pull-up'),
  ('German Hang', 'strength', 'full_body', 'free_weight', 'weight_reps', array[]::text[], 'german-hang'),
  ('Back Lever Tuck', 'strength', 'full_body', 'bodyweight', 'weight_reps', array[]::text[], 'back-lever-tuck'),
  ('Frog Stand', 'strength', 'glutes', 'free_weight', 'weight_reps', array[]::text[], 'frog-stand'),
  ('Hindu Squat', 'strength', 'quads', 'bodyweight', 'reps_only', array[]::text[], 'hindu-squat'),
  ('Butt Kick', 'strength', 'full_body', 'free_weight', 'weight_reps', array[]::text[], 'butt-kick'),
  ('Burpee Broad Jump', 'strength', 'full_body', 'bodyweight', 'reps_only', array[]::text[], 'burpee-broad-jump'),
  ('Arch Hold', 'strength', 'full_body', 'bodyweight', 'duration', array[]::text[], 'arch-hold'),
  ('Hanging Windshield Wiper', 'strength', 'full_body', 'free_weight', 'weight_reps', array[]::text[], 'hanging-windshield-wiper'),
  ('Tall Clean', 'strength', 'full_body', 'free_weight', 'weight_reps', array[]::text[], 'tall-clean'),
  ('Axle Deadlift', 'strength', 'hamstrings', 'free_weight', 'weight_reps', array[]::text[], 'axle-deadlift'),
  ('Sandbag Shouldering', 'strength', 'shoulders', 'free_weight', 'weight_reps', array[]::text[], 'sandbag-shouldering'),
  ('Stone Load', 'strength', 'full_body', 'free_weight', 'weight_reps', array[]::text[], 'stone-load'),
  ('B-Skip', 'cardio', 'cardio', 'bodyweight', 'duration', array[]::text[], 'b-skip'),
  ('Half Kneeling Lift', 'strength', 'full_body', 'free_weight', 'weight_reps', array[]::text[], 'half-kneeling-lift'),
  ('90/90 Hip Lift', 'strength', 'full_body', 'free_weight', 'weight_reps', array[]::text[], '90-90-hip-lift'),
  ('Cable Shrug', 'strength', 'traps', 'free_weight', 'weight_reps', array[]::text[], 'cable-shrug'),
  ('Machine Rear Delt', 'strength', 'back', 'machine', 'weight_reps', array['machine Rear Delt'], 'machine-rear-delt'),
  ('Chest Press Neutral Grip', 'strength', 'chest', 'free_weight', 'weight_reps', array[]::text[], 'chest-press-neutral-grip'),
  ('Single-Arm Landmine Press', 'strength', 'full_body', 'free_weight', 'weight_reps', array[]::text[], 'single-arm-landmine-press'),
  ('Single-Leg RDL', 'strength', 'hamstrings', 'free_weight', 'weight_reps', array[]::text[], 'single-leg-rdl'),
  ('Pause Hip Thrust', 'strength', 'glutes', 'free_weight', 'weight_reps', array[]::text[], 'pause-hip-thrust'),
  ('Seated Good Morning', 'strength', 'hamstrings', 'free_weight', 'weight_reps', array[]::text[], 'seated-good-morning'),
  ('Banded Push-Up', 'strength', 'full_body', 'bodyweight', 'distance', array[]::text[], 'banded-push-up'),
  ('Ring Support Hold', 'strength', 'full_body', 'bodyweight', 'duration', array[]::text[], 'ring-support-hold'),
  ('Tuck Front Lever Row', 'strength', 'back', 'bodyweight', 'weight_reps', array[]::text[], 'tuck-front-lever-row'),
  ('Dips Weighted', 'strength', 'triceps', 'free_weight', 'weight_reps', array[]::text[], 'dips-weighted'),
  ('Pull-Up Weighted', 'strength', 'back', 'free_weight', 'distance', array[]::text[], 'pull-up-weighted'),
  ('Chin-Up Weighted', 'strength', 'back', 'free_weight', 'weight_reps', array[]::text[], 'chin-up-weighted'),
  ('Walking Lunge Bodyweight', 'strength', 'quads', 'bodyweight', 'duration', array[]::text[], 'walking-lunge-bodyweight'),
  ('Bear Hug Sandbag Carry', 'strength', 'full_body', 'free_weight', 'distance', array[]::text[], 'bear-hug-sandbag-carry'),
  ('Sled March', 'strength', 'full_body', 'free_weight', 'duration', array[]::text[], 'sled-march'),
  ('Tempo Push-Up', 'strength', 'full_body', 'bodyweight', 'distance', array[]::text[], 'tempo-push-up'),
  ('Isometric Split Squat', 'strength', 'quads', 'bodyweight', 'reps_only', array[]::text[], 'isometric-split-squat'),
  ('Copenhagen Raise', 'strength', 'full_body', 'free_weight', 'weight_reps', array[]::text[], 'copenhagen-raise')
on conflict do nothing;

update public.exercises
set slug = trim(both '-' from regexp_replace(lower(name), '[^a-z0-9]+', '-', 'g'))
where created_by is null and (slug is null or slug = '');
